version: '3'

services:
    dispatcher:
        build: .
        #image: dispatcher
        ports:
            - 80:80
        
    site1:
        build: ./site1/
        depends_on:
            - dispatcher
        #image: site1
        
    #site2:
        #depends_on:
            #- dispatcher
        #image: site2
        