
services:
    dispatcher:
        build: .
        ports:
            - 80:80
        networks:
            - web
    site1:
        build: ./site1/
        depends_on:
            - dispatcher
        networks:
            - web

networks:
    web:
