version: '2'

services:
    reverseproxy:
        image: perezpardojc/dispatcher
        ports:
            - 80:80
        restart: always

    nginx:
        depends_on:
            - perezpardojc/dispatcher
        image: perezpardojc/site1
        restart: always

    apache:
        depends_on:
            - reverseproxy
        image: perezpardojc/site2
        restart: always      